# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-23 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
    ]
