# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2022-09-23 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20220923_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(blank=True, to='autor.Autor'),
        ),
    ]
