# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2022-09-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20220923_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Editor'),
        ),
    ]
